microsoft/hi-ml

setup.py
Closes #77 
Simple change to make our tagline on PyPi (i.e. [here](https://pypi.org/project/hi-ml/)) more concrete.
=> Tagline change

readthedocs_requirements.txt
https://readthedocs.org/dashboard/hi-ml/advanced/
Very simple PR
=> Adding the required requirements file for readthedocs

docs/source/examples.md, src/health/azure/azure_util.py, src/health/azure/download_aml_run.py, src/health/azure/examples/elevate_this.py, src/health/azure/himl.py, src/health/azure/run_tensorboard.py, testhiml/health/azure/test_azure_util.py, testhiml/health/azure/test_data/make_tests.py, testhiml/health/azure/test_data/simple/hello_world_template.txt, testhiml/health/azure/test_download_aml_run.py, testhiml/health/azure/test_himl.py, testhiml/health/azure/test_run_tensorboard.py
1. Change workspace_config_path to workspace_config_file
2. Similar path -> file changes in arguments  for run_tensorboard and download_aml_run
3. Cleanup duplicated code in examples.md
=> Arg name changes including scripts and submit_to_azure_if_needed

.github/workflows/check_changelog.yml, .gitignore, CHANGELOG.md, MANIFEST.in, docs/Makefile, docs/source/first_steps.md, docs/source/index.rst, package_description.md, setup.py, src/health/azure/himl.py
Adding a changelog, displaying it with the docs, and ensuring it is updated in each PR.
=> Adding changelog

CHANGELOG.md, docs/source/developers.md, hi-ml/src/health_ml/utils/logging.py, hi-ml/testhiml/testhiml/utils/test_logging.py, pyrightconfig.json
Simplify release process to no longer require a PR.
=> Document updated release process

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .vscode/launch.json, CHANGELOG.md, Makefile, docs/source/datasets.md, docs/source/examples/8/sample.py, hi-ml-azure/Makefile, hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/src/health_azure/examples/elevate_this.py, hi-ml-azure/src/health_azure/examples/environment.yml, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_data/make_tests.py, hi-ml-azure/testazure/testazure/test_data/simple/hello_world_template.txt, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-azure/testazure/testazure/test_run_tensorboard.py, hi-ml-azure/testazure/testazure/util.py, hi-ml/Makefile, hi-ml/testhiml/testhiml/utils/slide_image_loading/src/profile_load_image.py, test_requirements.txt
Write a detailed description of your PR here.
=> Locally mount datasets

CHANGELOG.md, hi-ml-azure/pytest.ini, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml/run_requirements.txt, hi-ml/src/health_ml/utils/reports.py, hi-ml/testhiml/testhiml/utils/test_logging.py, hi-ml/testhiml/testhiml/utils/test_reports.py
Add an HTML reporting tool that can display text, images and tables for presenting experiment results.
As part of this we also add a function for downloading any files from HyperDrive run children.
=> Add HTML report

CHANGELOG.md, hi-ml-azure/src/health_azure/himl_download.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_datasets.py, hi-ml-azure/testazure/testazure/test_himl_download.py, hi-ml/run_requirements.txt, hi-ml/src/health_ml/networks/layers/attention_layers.py, hi-ml/src/health_ml/utils/bag_utils.py, hi-ml/src/health_ml/utils/box_utils.py, hi-ml/src/health_ml/utils/common_utils.py, hi-ml/src/health_ml/utils/data_augmentations.py, hi-ml/testhiml/testhiml/test_attentionlayers.py, hi-ml/testhiml/testhiml/test_bag_utils.py, hi-ml/testhiml/testhiml/test_data_augmentations.py, hi-ml/testhiml/testhiml/utils/slide_image_loading/src/Histopathology/datasets/panda_dataset.py, hi-ml/testhiml/testhiml/utils/slide_image_loading/src/Histopathology/preprocessing/create_tiles_dataset.py, hi-ml/testhiml/testhiml/utils/test_logging.py, hi-ml/testhiml/testhiml/utils/test_reports.py
Add utils for:
- Bag sampling
- Bounding boxes
- HEDJitter & Stain normalisation
And add attention layers
=> Add utils and attention layers

CHANGELOG.md, hi-ml-azure/src/health_azure/utils.py, hi-ml/src/health_ml/utils/reports.py, hi-ml/testhiml/testhiml/utils/test_reports.py
Make improvements to report tool including:
- allow lists of tables
- add optional base64 encoding of images
- add method to zip report folder
=> Make improvements to report tool 

CHANGELOG.md, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILECrck.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILEPanda.py
These changes were recently merged into innereye-dl: https://github.com/microsoft/InnerEye-DeepLearning/commit/1600ef3ddfa83328ec35d179533c3a4e95f88a69, this PR moves them to hi-ml.
=> update DeepSMILE models

hi-ml/src/health_ml/deep_learning_config.py
This ports the fix from https://github.com/microsoft/InnerEye-DeepLearning/pull/622 to hi-ml
=> FIX: Output directories of multi-GPU DDP can be wrong

.vscode/launch.json, CHANGELOG.md, hi-ml-azure/src/health_azure/datasets.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
* Enable mounting for datasets in AzureML
* On runs outside of AzureML, mount datasets by default
---
Please follow the guidelines for PRs contained [here](/CONTRIBUTING.md). Checklist:
When completing your PR, you will be asked for a title and an optional extended description. By default, the extended description will be a concatenation of the individual
commit messages. Please DELETE/REPLACE that with a human readable extended description for non-trivial PRs.
=> ENH: Dataset mounting is now configurable

CHANGELOG.md, hi-ml/testhiml/testhiml/test_attentionlayers.py
Transformer pooling test failed sometimes when testing batch_size=1 due to rounding issues. Added a tolerance similar to allclose.
=> BUG: Added tolerance to test

hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
Setting a display name and tag for run and hyperdrive child runs
---
Please follow the guidelines for PRs contained [here](/CONTRIBUTING.md). Checklist:
When completing your PR, you will be asked for a title and an optional extended description. By default, the extended description will be a concatenation of the individual
commit messages. Please DELETE/REPLACE that with a human readable extended description for non-trivial PRs.
=> ENH: Adding tag argument to specify display name

hi-ml-histopathology/Makefile, hi-ml-histopathology/README.md, hi-ml-histopathology/environment.yml
Pin package versions in hi-ml-histopathology/environment.yml to avoid environment discrepancies.
=> BUG: Pin package versions for histopathology

CHANGELOG.md, hi-ml-histopathology/src/SSL/lightning_containers/ssl_container.py
As seen in https://arxiv.org/abs/1706.02677, we automatically rescale the learning rate by the number of GPUs to train.
=> ENH: Linearly scale the learning rate of ssl models

.vscode/settings.json
Make title and activity bar a distinct color to be able to tell multiple editor windows apart
=> ENH: Add colors to the VSCode  window

.vscode/settings.json, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/utils/type_annotations.py, hi-ml/testhiml/testhiml/test_model_trainer.py
Updates pl_limit_train_batches and pl_limit_val_batches to accept float types
=> BUG: Params pl_limit_train(/val)_batches should accept float

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_himl.py
Environment variables should now be set in RunConfiguration.
=> BUG: Remove outdated SDK usage

hi-ml-azure/testazure/testazure/test_traverse.py
Mypy was passing on the PR build #252, but later failed in CI
=> BUG: MyPy error showing in CI

hi-ml-histopathology/testhisto/testhisto/datamodules/test_slides_datamodule.py, hi-ml-histopathology/testhisto/testhisto/models/test_deepmil.py
Please make sure to follow all the tasks in the checklist below. Then, delete this line and write a detailed description of your pull request here.
=> BUG: HOTFIX skip pathmnist tests

hi-ml-histopathology/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/run_ml.py, hi-ml/src/health_ml/utils/checkpoint_handler.py, hi-ml/src/health_ml/utils/checkpoint_utils.py, hi-ml/src/health_ml/utils/common_utils.py, hi-ml/testhiml/testhiml/test_deep_learning_config.py, hi-ml/testhiml/testhiml/test_run_ml.py, hi-ml/testhiml/testhiml/test_runner.py
Models that use a custom logic for choosing best checkpoints can't presently use those for inference. This PR adds a method to the container to control that.
=> ENH: Add ability to override which checkpoint to use for inference

new_project_template/environment.yml
(Picked up by `pre-commit`).
Online validator: https://codebeautify.org/yaml-validator/y22f4ba39
=> BUG: Fix invalid environment file

hi-ml-histopathology/src/histopathology/configs/classification/BaseMIL.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILESlidesPandaBenchmark.py, hi-ml-histopathology/src/histopathology/datamodules/panda_module_benchmark.py, hi-ml-histopathology/src/histopathology/models/encoders.py, hi-ml/src/health_ml/networks/layers/attention_layers.py
Add DeepSMILESlidesPandaBenchmark config
=> ENH: Add DeepSMILESlidesPandaBenchmark config

.github/workflows/hi-ml-pr.yml, .github/workflows/histopathology-pr.yml
Also retiring the testing of the `*.tar.gz` packages
=> ENH: Upload Codecov results also when tests fail

.pre-commit-config.yaml
This is too intrusive for now, and we need to better understand how this tool works. I've asked for clarifications at
- https://github.com/pre-commit-ci/issues/issues/125
=> STYLE: Disable pre-commit CI autofixes

hi-ml-histopathology/Makefile
Remove Makefile command for TilesPANDA regression test since it turns out we don't have a good Run to compare performance to
=> DEL: Remove TilesPANDA regression test

.pre-commit-config.yaml
=> STYLE: Set default PR title for pre-commit CI bot

docs/source/runner.md, hi-ml/src/health_ml/configs/hello_world.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
Account for additional comment on auto merged #420
=> DOC: Fix out of sync docs and typo

.github/workflows/codeql-analysis.yml, .github/workflows/credscan.yml
Adding a credential scanner also as a github workflow because we have had issues with the ADO-based one.
=> ENH: Add Credential Scanning Workflow

hi-ml-histopathology/src/histopathology/configs/SSL/CRCK_SimCLRContainer.py, hi-ml-histopathology/src/histopathology/configs/SSL/PANDA_SimCLRContainer.py
=> ENH: Reduce console logging noise

hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-azure/testazure/testazure/test_run_tensorboard.py
* Change the test dataset for testing mounting from "panda" to "hello_world"
* Remove a time-consuming docker build step to test tensorboard (cut PR time from 46min to 26min)
=> BUG: Workflows time out because of using a too large test dataset

.pre-commit-config.yaml, hi-ml-multimodal/src/health_multimodal/image/data/io.py
I'm going to introduce a formatting issue next, to make sure the bot fixes it.
=> ENH: Enable pre-commit CI autofixes

.github/workflows/credscan.yml
=> BUG: Restrict CredScan action to credential scanning only

.github/workflows/multimodal-pr.yml, hi-ml-multimodal/Makefile, hi-ml-multimodal/notebooks/phrase_grounding.ipynb, hi-ml-multimodal/src/health_multimodal/image/__init__.py
=> BUG: Fix demo notebook failing on PRs

hi-ml-histopathology/src/histopathology/scripts/mount_azure_dataset.py
=> BUG: Mounted dataset disappears when mount script terminates

docs/source/azure_setup.md
- Fix a missing linebreak
- Add documentation to use SAS
=> DOC: Improve Azure setup instructions

hi-ml-histopathology/src/histopathology/utils/plots_utils.py, hi-ml-histopathology/testhisto/testhisto/utils/test_plots_utils.py
Closes [this issue](https://github.com/microsoft/hi-ml/issues/508)
=> BUG: Plot conf matrix when not all labels present

docs/source/panda_model.md
Please make sure to follow all the tasks in the checklist below. Then, delete this line and write a detailed description of your pull request here.
=> FIX: Fixing typo in panda_model.md

hi-ml-multimodal/MANIFEST.in, hi-ml-multimodal/setup.py
- Simplified `setup.py` in `hi-ml-multimodal` as we are not using CI for these purposes.
- Set initial PyPI version to `0.1.0` as recommended in [Semantic Versioning 2.0.0](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
- Added `MANIFEST.in`, needed to include files such as `requirements_*.txt`, `README` and `LICENSE` in the package distribution
- Tried TestPyPI by running the commands below (from [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/))
```console
cd hi-ml-multimodal
python3 -m pip install --upgrade build
python3 -m build
python3 -m pip install --upgrade twine
python3 -m twine upload --repository testpypi dist/*
```
=> MNT: Prepare hi-ml-multimodal for PyPI

docs/source/panda_model.md
Please make sure to follow all the tasks in the checklist below. Then, delete this line and write a detailed description of your pull request here.
=> DOC: Fix broken links in cpath documentation

docs/source/runner.md, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml-cpath/src/health_cpath/utils/deepmil_utils.py, hi-ml-cpath/src/health_cpath/utils/naming.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/run_ml.py, hi-ml/src/health_ml/utils/checkpoint_handler.py, hi-ml/testhiml/testhiml/test_deep_learning_config.py, hi-ml/testhiml/testhiml/test_run_ml.py
Add flags `pretrain_encoder pretrainer_pooling pretrain_classifier` to init submodules weights from a pretrained checkpoint in `src_checkpoint`
=> ENH: Enable flexible weights initialization from src_checkpoint

docs/source/panda_model.md, hi-ml-azure/run_pytest.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-cpath/Makefile, hi-ml-cpath/src/health_cpath/utils/output_utils.py, hi-ml-multimodal/MANIFEST.in, hi-ml-multimodal/requirements_run.txt, hi-ml-multimodal/setup.py, hi-ml-multimodal/src/health_multimodal/__init__.py, hi-ml-multimodal/src/health_multimodal/image/__init__.py, hi-ml-multimodal/src/health_multimodal/image/model/__init__.py, hi-ml-multimodal/src/health_multimodal/image/model/model.py, hi-ml-multimodal/src/health_multimodal/image/model/resnet.py, hi-ml-multimodal/src/health_multimodal/image/utils.py, hi-ml-multimodal/src/health_multimodal/text/utils.py, hi-ml-multimodal/test_multimodal/image/model/test_model.py, hubconf.py
Updating transfer_main to main
- bug fixes to handle error in saving outputs
- integration test
=> ENH: Updating transfer_main to main

hi-ml-azure/run_requirements.txt, hi-ml-cpath/src/SSL/lightning_modules/ssl_online_evaluator.py, hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml/src/health_ml/run_ml.py, hi-ml/testhiml/testhiml/test_model_trainer.py, hi-ml/testhiml/testhiml/test_run_ml.py
A couple of fixes to remove some of the noise from logs from running the runner
=> ENH: Clean up logs

hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py
Best metric checkpoint should reflect the primary metric of choice and whether the goal was to maximise or minimise
=> FIX: Fix best checkpoint name 

.github/workflows/multimodal-pr.yml, hi-ml-multimodal/notebooks/phrase_grounding.ipynb
Updating the phrase grounding demo to consume `hi-ml-multimodal` from PyPI instead of GitHub.
=> MNT: Install PyPI package in demo notebook

hi-ml-cpath/src/health_cpath/models/transforms.py, hi-ml-cpath/testhisto/conftest.py, hi-ml-cpath/testhisto/testhisto/mocks/tiles_generator.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml-cpath/testhisto/testhisto/models/test_transforms.py
Add parameter to control tiles intensity scaling to be able to run augmentations on uint8 data to save some memory and speed up computations.
=> ENH: Parameterize tiles intensity scaling

hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILECrck.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILEPanda.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILESlidesPandaBenchmark.py, hi-ml-cpath/src/health_cpath/models/encoders.py, hi-ml-cpath/src/health_cpath/utils/deepmil_utils.py, hi-ml-cpath/testhisto/testhisto/mocks/container.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml-cpath/testhisto/testhisto/models/test_encoders.py, hi-ml-cpath/testhisto/testhisto/models/test_transforms.py
Add specific ImageNet encoders for transferability study: Resnet18/50 with and without preproc
=> ENH: Add specific ImageNet encoders for transferability study

.github/workflows/cpath-pr.yml, hi-ml-cpath/Makefile, hi-ml-cpath/src/health_cpath/models/deepmil.py
Predicted labels should be integers.
=> BUG: Cast binary labels into integers.

hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/run_ml.py
Add a log to print the epoch of best checkpoint.
=> ENH: Log epoch of best checkpoint

hi-ml-cpath/environment.yml, hi-ml-cpath/requirements_test.txt, new_project_template/requirements_test.txt, test_requirements.txt
Some CI tests are failing due to incompatibilities between linting packages. This PR will hopefully fix those.
=> MNT: Upgrade linting packages

.amltignore, docs/source/runner.md, docs/source/submitting_via_amulet.md, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-cpath/amlt_singularity_cpath.yml, hi-ml-cpath/src/health_cpath/datasets/default_paths.py, hi-ml/src/health_ml/configs/hello_world.py, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/model_trainer.py, hi-ml/src/health_ml/run_ml.py, hi-ml/src/health_ml/runner.py, hi-ml/src/health_ml/utils/logging.py, hi-ml/testhiml/testhiml/test_run_ml.py, hi-ml/testhiml/testhiml/test_runner.py, hi-ml/testhiml/testhiml/utils/test_logging.py
Add code from PRs 
- #580 ENH: Enable logging to AzureML when running training outside AzureML
- #588 FIX: Update env var settings for multi node
- #597 ENH: Add a way of quickly starting runs with different seeds
- #596 ENH: Submit jobs to Singularity via Amulet
=> ENH: Add essential changes from main

hi-ml-multimodal/src/health_multimodal/common/visualization.py
This is helpful when using e.g. Streamlit to capture and display the plotted figure.
=> ENH: Return figure when plotting similarity map

hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml/environment.yml
Use newer API for blob deletion
=> MNT: Update test helpers to work with latest AML package

docs/source/amulet_overview.md, hi-ml-cpath/amlt_singularity_cpath.yml, hi-ml/src/health_ml/runner.py
Set additional tags to Amulet jobs beside amlt-expr-name.
=> ENH: Set additional tags to Amulet Jobs

hi-ml-cpath/src/health_cpath/utils/callbacks.py
Add kwargs to avoid confusion and remove double heatmap_folder
=> BUG: Fix double root folder for heatmaps

docs/source/amulet/config.yml
Cherry pick #624 to transfer_main.
=> MNT: Fix YAML syntax for Amulet jobs (#624)

hi-ml-cpath/Makefile, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml-cpath/src/health_cpath/utils/callbacks.py, hi-ml-cpath/src/health_cpath/utils/naming.py, hi-ml-cpath/testhisto/conftest.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml-cpath/testhisto/testhisto/utils/test_callbacks.py
Add entropy values to detect ambiguity and track validation loss during training
=> ENH: Track validation loss and add entropy value

hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py
Fix for the checkpoint path (of the best metrics checkpoint) not being correctly picked up on the cluster.
=> BUG: Checkpoint path not picked up correctly

hi-ml-azure/testazure/testazure/test_datasets.py, hi-ml/src/health_ml/run_ml.py, hi-ml/testhiml/testhiml/test_run_ml.py
Add extra validation of model weights with checkpoint
=> ENH: Validate model weights before inference

hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/datasets/panda_dataset.py, hi-ml-cpath/src/health_cpath/utils/output_utils.py, hi-ml-cpath/src/health_cpath/utils/plots_utils.py, hi-ml-cpath/src/health_cpath/utils/viz_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_viz_utils.py
Use LoadROId for WSI without masks.
=> ENH: Enable heatmaps and thumbnails plots for WSI without masks

hi-ml-cpath/src/health_cpath/datamodules/base_module.py
Always shuffle tiles in BagDataset.
=> BUG: Set instance shuffling to True

hi-ml/src/health_ml/run_ml.py, hi-ml/testhiml/testhiml/test_run_ml.py
Kill DDP processes after run_training and initialize a new trainer instance with a single device for inference
=> ENH: Run extra validation epoch on a single gpu

hi-ml-cpath/src/health_cpath/utils/wsi_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_wsi_utils.py, hi-ml/src/health_ml/utils/data_augmentations.py, hi-ml/testhiml/testhiml/test_data_augmentations.py
Adjust the input/output shapes.
=> ENH: Extend StainNormalisation Transform to work with Slides Pipeline

hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/model_trainer.py
Add log_every_n_steps trainer parameter
=> ENH: Add log every nsteps parameter

hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/datamodules/base_module.py, hi-ml-cpath/src/health_cpath/utils/output_utils.py, hi-ml-cpath/src/health_cpath/utils/plots_utils.py, hi-ml-cpath/src/health_cpath/utils/viz_utils.py, hi-ml-cpath/testhisto/testhisto/datamodules/test_slides_datamodule.py, hi-ml-cpath/testhisto/testhisto/utils/test_viz_utils.py
Add wsi_reader_args to be able to use different backend ...
=> ENH: Parameterize CuCim backend

hi-ml-cpath/environment.yml, hi-ml-cpath/requirements_run.txt, hi-ml-multimodal/requirements_run.txt, hi-ml/environment.yml, hi-ml/run_requirements.txt
=> ENH: Fix security Alerts

docs/source/README.md, docs/source/multimodal.md
=> BUG: Add symbolic link that had gotten deleted by accident

hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
Add workspace_config_path param
=> ENH: Enable custom workspace config path

.github/actions/cancel_azureml_jobs/cancel_aml_jobs.py
Replace all non-alphanumeric characters (except single underscores) in experiment name with underscores
=> FIX: Replace special characters in experiment name with underscores

.codecov.yml, .github/workflows/multimodal-pr.yml, hi-ml-multimodal/Makefile, hi-ml-multimodal/pytest.ini, hi-ml-multimodal/requirements_test.txt
=> TEST: Update CI to compute and upload coverage for hi-ml-multimodal

hi-ml-multimodal/src/health_multimodal/text/data/io.py
This is the first PR to address the issue raised in
- #445
=> ENH: Use module-level logger in hi-ml-multimodal

.github/actions/cancel_azureml_jobs/cancel_aml_jobs.py, .github/workflows/cpath-pr.yml, .github/workflows/hi-ml-pr.yml, hi-ml-cpath/.vscode/launch.json, hi-ml-cpath/Makefile, hi-ml-cpath/testSSL/conftest.py, hi-ml-cpath/testhisto/conftest.py, hi-ml/src/health_ml/runner.py, hi-ml/src/health_ml/utils/logging.py
* Run `pytest` and `pytest` on GPUs in parallel rather than sequentially.
* Cancel existing runs from previous pushes
* Fix dependency problem in hi-ml PR
* Reduce logging noise from `numba`
=> ENH: Improve PR workflows

new_project_template/package_description.md
Clarify that `hi-ml-newproject` is not an actual package
=> ENH: Clean up readme file in the template for new projects

hi-ml/src/health_ml/run_ml.py
Recreate the datamodule for extra validation and inference, this is useful to reflect any changes in datamodule params (max_bag_size_inf=0 for whole slide inference)
=> ENH: Recreate datamodule for extra validation and inference

Makefile, hi-ml-azure/Makefile, hi-ml-cpath/Makefile, hi-ml-multimodal/Makefile, hi-ml/Makefile
There can be `mypy` cache folders at multiple levels of folder hierarchy, remove them all
=> ENH: Remove mypy cache folder in `make clean`

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml/src/health_ml/runner.py
=> BUG: Do not remove conda_env argument when submitting with SDK v2

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
Jobs fail saying that the dataset URI is malformed
=> BUG: SDK v2 datasets are not passed to AML correctly

hi-ml-azure/run_requirements.txt, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-cpath/environment.yml, hi-ml/environment.yml
=> BUG: Jobs on Kubernetes compute don't see GPUs

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_data/make_tests.py, hi-ml-azure/testazure/testazure/test_data/simple/hello_world_template.txt, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-azure/testazure/testazure/utils_testazure.py
Closes (for real) #773 . This fixes a bug that was left in #774
=> BUG: Display name is not respected when using SDK v2

hi-ml-cpath/src/health_cpath/utils/wsi_utils.py
Parametrize scale factor for intensity threshold
=> ENH: Add intensity threshold scale argument

hi-ml-cpath/src/health_cpath/models/deepmil.py
=> BUG: Fix missing bottom coordinates in outputs csv

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
=> BUG: Fix ordering of `local_datasets`

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_data/make_tests.py, hi-ml-azure/testazure/testazure/test_data/simple/hello_world_template.txt, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
=> BUG: Add flag for identity-based data access

.github/workflows/multimodal-pr.yml
Enable multimodal CI schedule, every morning at 4 AM UTC.
=> MNT: Run multimodal CI every morning

hi-ml-cpath/.vscode/launch.json, hi-ml-cpath/src/health_cpath/utils/girder.py
- Choose a split (test/extra_val/val) to upload
- Modify launch.json to use merged certificate file
=> ENH: Add an argument to specify split for DSA upload

.github/workflows/multimodal-pr.yml, hi-ml-multimodal/notebooks/phrase_grounding.ipynb
=> MNT: Increase verbosity while running notebook

hi-ml-cpath/src/health_cpath/preprocessing/tiff_conversion.py, hi-ml-cpath/testhisto/testhisto/mocks/slides_generator.py, hi-ml-cpath/testhisto/testhisto/preprocessing/test_tiff_conversion.py
Add resolution_unit param to Mock slides generator
=> ENH: Enable flexible resolution unit for mock data generator

hi-ml-cpath/src/health_cpath/preprocessing/loading.py, hi-ml-cpath/testhisto/conftest.py, hi-ml-cpath/testhisto/testhisto/datamodules/test_slides_datamodule.py, hi-ml-cpath/testhisto/testhisto/preprocessing/test_loading.py, hi-ml-cpath/testhisto/testhisto/utils/test_plots_utils.py
LoadMaskSubROId loads a sub section from a slide based a foreground png mask with categorical labels for each tissue section.
=> ENH: Add LoadMaskSubROId transform

hi-ml-cpath/src/health_cpath/preprocessing/tiff_conversion.py, hi-ml-cpath/testhisto/testhisto/preprocessing/test_tiff_conversion.py
=> BUG: Convert to tifffile if file doesn't exist or if it's empty

docs/source/datasets.md, hi-ml-azure/src/health_azure/datasets.py
=> ENH: Expose v1 dataset overwrite

hi-ml-cpath/src/health_cpath/preprocessing/tiff_conversion.py, hi-ml-cpath/src/health_cpath/utils/tiff_conversion_config.py, hi-ml-cpath/testhisto/testhisto/preprocessing/test_tiff_conversion.py
Add min_file_size and verbose flags to tiff conversion config
=> ENH: Add diagnosis for Tiff Conversion

hi-ml-multimodal/.bumpversion.cfg, hi-ml-multimodal/Makefile, hi-ml-multimodal/setup.py, hi-ml-multimodal/src/health_multimodal/__init__.py
```shell
cd hi-ml-multimodal
```
Bump version:
```shell
make bump_version_dry part=patch  # testing
make bump_version part=patch
```
Publish:
```shell
make bump_version_dry part=patch  # username: "__token__". password: [your TestPyPI token]
make bump_version part=patch  # username: [your PyPI username]. password: [your PyPI password]
```
=> MNT: Bump hi-ml-multimodal version: 0.2.0 → 0.2.1

hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py
=> FIX: Stop replacing dashes with underscores in experiment name

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
=> BUG: AmlIgnore file should not lose its last linebreak

hi-ml-azure/src/health_azure/amulet.py, hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/himl_tensorboard.py, hi-ml-azure/src/health_azure/logging.py, hi-ml-azure/src/health_azure/paths.py, hi-ml-azure/src/health_azure/traverse.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_datasets.py
Within `hi-ml-azure`, clean up all calls to `logging` and replace with correctly created module-level logger objects
=> ENH: Make logging consistent

.github/workflows/cpath-pr.yml, .github/workflows/hi-ml-pr.yml, .github/workflows/multimodal-pr.yml, new_project_template/new-project-pr.yml
Ubuntu 20.04 has reached end of life
=> MNT: Upgrade workflows to latest Ubuntu
