.github/workflows/build-test-pr.yml, setup.py
Closes #79 
Our code in `setup.py` will trigger with new tags. `setuptools.setup` will reject tags that are not release versions but we could do more to make that explicit by checking for the leading "v".
Also when we tag releases as, say, "v0.1.1" the leading "v" is carried through `setuptools.setup` so it becomes part of the pip test download
> Successfully installed pip-21.2.4
> Collecting hi-ml==v0.1.0
>   Downloading hi_ml-0.1.0-py3-none-any.whl (25 kB)
(from [here](https://github.com/microsoft/hi-ml/runs/3362573497?check_suite_focus=true#step:6:29))
This works, but it would be cleaner to submit the version number using the public version identifier format mandated in [PEP 440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers), i.e. without the leading "v"
A …
=> adding v to GITHUB_REF_TAG_COMMIT

src/health/azure/himl.py
Closes #82 
`submit_to_azure_if_needed` has just one parameter which has no default, `compute_cluster_name`. But some consumers of our package (e.g. InnerEye) may have the option to train a model locally. In that situation we intend them to still call `submit_to_azure_if_needed` (that's why it is called _if_needed_) but for a purely local run why should they have a  `compute_cluster_name`? It should also have a default, `""`.
=> compute_cluster_name should not be required local

CHANGELOG.md, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
After register_environment returns our retrieved environment, we aren't using it anywhere. This is a fix to update the environment property of run_config with the retrieved environment
=> Bug fix: update run_config with registered environment

CHANGELOG.md, docs/source/loading_images.md, hi-ml/testhiml/testhiml/utils/image_loading/profile_image_loading.py
Write a detailed description of your PR here.
=> Profile loading png as np

CHANGELOG.md, hi-ml-azure/testazure/testazure/test_himl.py
70_driver_log.txt has moved under the new azure runtime.
=> Check other folders for driver_log

CHANGELOG.md, hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/testazure/testazure/test_datasets.py
Using an empty string as the target_folder in DatasetConfig creates an AML download location that is ".", which makes the job logic choke.
Fixes #160 
=> Fix for invalid "." dataset location in AzureML

CHANGELOG.md, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py
This PR contains changes to the class CheckpointDownloader to fix a bug with the hierarchies of the downloaded folders.
=> Fixing checkpoint downloader

CHANGELOG.md, hi-ml-histopathology/src/histopathology/models/deepmil.py, hi-ml-histopathology/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/model_trainer.py, hi-ml/src/health_ml/utils/logging.py, hi-ml/testhiml/testhiml/test_split_dataset.py
Fixes a bug in `DeepMILModule` whereby predicted hard labels were being passed to classification metrics, instead of the intended continuous probability scores. This PR also adds tests to ensure this won't happen anymore.
=> Fix DeepMIL metrics bug

CHANGELOG.md, hi-ml-histopathology/src/histopathology/models/transforms.py, hi-ml-histopathology/testhisto/testhisto/models/test_transforms.py, hi-ml/src/health_ml/utils/data_augmentations.py
PR to add a transformation adaptor to allow transformations working only on Tensors/Images to work with a dict in input
=> Adding transformation adaptor

CHANGELOG.md, hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/testazure/testazure/test_datasets.py
The current error message is
```
Datastore X was not found in the workspace. Existing datastores: A, B, C
```
I have just modified to include the workspace name:
```
Datastore "X" was not found in the "Y" workspace. Existing datastores: A, B, C
```
=> Show workspace name in error message

hi-ml-azure/src/health_azure/paths.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml/src/health_ml/configs/hello_world.py, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/runner.py, hi-ml/src/health_ml/utils/common_utils.py, hi-ml/testhiml/testhiml/utils/fixed_paths_for_tests.py, hi-ml/testhiml/testhiml/utils/slide_image_loading/src/Histopathology/datasets/panda_dataset.py
Config loader fails depending on whether runner is called via path that involves `..` or not.
Bug fix is the change in `runner.py`, all other changes are just places where we might get wrong results because of `Path.absolute`
Other changes improve search for conda environment files in corner cases
=> FIX: Config loader fails when using relative directories

hi-ml-histopathology/src/histopathology/datamodules/base_module.py
One line fix to avoid cache being reused when cache_mode is None. It also allows to run the debugger in vscode without being forced to manually remove the cache
=> FIX: update base_module to avoid cache being reused when cachemode is None

hi-ml-azure/src/health_azure/utils.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py, hi-ml/testhiml/testhiml/test_runner.py
* Runner now has argument for docker shm size, and prints the defaults when used with --help
* Fix for wrong path in multi-GPU setting
---
Please follow the guidelines for PRs contained [here](/CONTRIBUTING.md). Checklist:
When completing your PR, you will be asked for a title and an optional extended description. By default, the extended description will be a concatenation of the individual
commit messages. Please DELETE/REPLACE that with a human readable extended description for non-trivial PRs.
=> ENH: Runner specifies docker image size, prints defaults

hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-histopathology/src/histopathology/utils/output_utils.py
Adds a `health_azure.utils.replace_directory()` function to enable "renaming" folders in AML runs (in practice: clear destination, copy contents, delete originals). The special logic is necessary because blob storage does not allow directly moving/renaming files. 
This change should fix an issue with `DeepMILOutputsHandler` running in AML, whereby it needs to move previous-best validation outputs to a temporary folder to avoid partial overwrites.
=> BUG: Fix renaming of outputs folders in Azure ML

.github/pull_request_template.md
Instead of having to manually delete the PR checklist, this PR hides it using an HTML comment block.
=> DOC: Hide checklist in PR template

hi-ml-histopathology/src/histopathology/configs/classification/BaseMIL.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILECrck.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILEPanda.py, hi-ml-histopathology/src/histopathology/datamodules/panda_module.py, hi-ml-histopathology/src/histopathology/datamodules/tcga_crck_module.py, hi-ml/src/health_ml/utils/split_dataset.py, hi-ml/testhiml/testhiml/test_attentionlayers.py
Moved the necessary code for cross validation from innereye-dl to himl.
Have two runs here that work fine:
CRCk: https://ml.azure.com/experiments/id/16a5dbdd-67ef-4801-9799-130ebd08a5a9/runs/HD_d76ef6cd-0403-4923-b8fa-dfd2827c5d74?wsid=/subscriptions/db9fc1d1-b44e-45a8-902d-8c766c255568/resourceGroups/innereyerg/providers/Microsoft.MachineLearningServices/workspaces/innereye4ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
PANDA: https://ml.azure.com/experiments/id/9a7412d2-f9ec-4a65-baa3-15e7995ad867/runs/HD_b5594f0e-c190-4357-b623-6b19121de1dc?wsid=/subscriptions/db9fc1d1-b44e-45a8-902d-8c766c255568/resourceGroups/innereyerg/providers/Microsoft.MachineLearningServices/workspaces/innereye4ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
=> BUG: Move cross validation function from innereye-dl to himl

hi-ml-histopathology/src/histopathology/models/deepmil.py, hi-ml-histopathology/src/histopathology/utils/metrics_utils.py, hi-ml-histopathology/src/histopathology/utils/output_utils.py, hi-ml-histopathology/testhisto/testhisto/utils/test_output_utils.py, hi-ml-histopathology/testhisto/testhisto/utils/utils_testhisto.py
This PR ensures that epoch results passed to an outputs handler are synchronised (i.e. gathered) across DDP processes, and the processing and saving of the gathered outputs now happens only on the global rank-0 process. Fixes #259.
Also includes a check for empty list in `metrics_utils.select_k_tiles()` to fix #260.
=> BUG: Enable outputs handler to work in DDP

CHANGELOG.md, hi-ml/run_requirements.txt
Pin version of jinja2 to avoid bug in latest version (3.1.0) that causes the following error: `AttributeError: module 'jinja2' has no attribute 'Markup'`
Related to [this issue](https://github.com/microsoft/hi-ml/issues/263l)
=> BUG: Pin jinja2 to avoid bug in latest version

.vscode/settings.json, CHANGELOG.md
PYTHONPATH for windows - multiple entries should be separated with ';' as [described here](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH)
=> BUG: Correct pythonpath separator character in VS code settings file

hi-ml-azure/testazure/testazure/test_azure_util.py
Test pipeline fails occasionally when testing download from Azure because files already exist.
=> BUG: Fix spurious test errors

hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py
When merging conda environments, we should also split on semicolons (and retain the text after the semicolon) as in the case ```package_name==version; platform_system=="Linux"```. Here we add the code to handle that case.
Resolves [this issue](https://github.com/microsoft/hi-ml/issues/269)
=> BUG: Conda environment file merging should also split on semicolons

hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILECrck.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILEPanda.py, hi-ml-histopathology/src/histopathology/datamodules/base_module.py, hi-ml-histopathology/src/histopathology/datamodules/panda_module.py, hi-ml-histopathology/src/histopathology/datamodules/tcga_crck_module.py
Enables passing keyword arguments to the dataloaders returned by a `TilesDataModule`. With this, we can now customise settings like `num_workers`, which massively accelerates experiments without caching (e.g. fine-tuning runs).
Note that `num_workers > 0` does not work if the encoder forward pass happens in the dataloader workers (i.e. how we currently do feature caching), as this is only allowed in the main process (or DDP processes).
=> ENH: Add dataloader kwargs in tiles data modules, including num_workers

hi-ml/run_requirements.txt
PR build breaks as of today with the release of Lightnig 1.6.0. Pin the version as a hotfix.
=> BUG: Hotfix for breaking changes in Pytorch Lightning 1.6.0

hi-ml-histopathology/src/histopathology/configs/classification/BaseMIL.py, hi-ml-histopathology/src/histopathology/utils/output_utils.py, hi-ml-histopathology/testhisto/testhisto/utils/test_output_utils.py
This is a bug fix for the error raised when trying to save slides_dataset as a hyperparameter by deepmil lightning module. The slides_dataset should be set out of the constructor.
=> BUG: Workaround to avoid saving a dataframe as a hyperparameter

.amlignore, .github/workflows/build-test-pr.yml, .gitignore, .vscode/launch.json, .vscode/settings.json, hi-ml-azure/pytest.ini, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-azure/testazure/testazure/utils_testazure.py, hi-ml-histopathology/README.md, hi-ml-histopathology/environment.yml, hi-ml-histopathology/pytest.ini, hi-ml-histopathology/testSSL/testSSL/test_ssl_containers.py, hi-ml-histopathology/testSSL/testSSL/utils.py, hi-ml-histopathology/testhisto/testhisto/utils/test_output_utils.py, hi-ml-histopathology/testhisto/testhisto/utils/utils_testhisto.py, hi-ml/pytest.ini, hi-ml/run_pytest.py
Add GPU tests to the histopathology folder.
=> ENH: Add step for GPU tests on the histo folder

hi-ml-histopathology/src/histopathology/models/deepmil.py, hi-ml-histopathology/src/histopathology/utils/naming.py, hi-ml-histopathology/src/histopathology/utils/output_utils.py
We've identified a memory leak in `DeepMILModule._shared_step()`: the `results` dictionary contains several GPU tensors. Lightning accumulates references to all outputs of each `training/validation/test_step()`, to be passed into `training/validation/test_epoch_end()`. This means the GPU memory is only freed at the end of an epoch.
The main issue that has been causing many CUDA out-of-memory errors is that, when fine-tuning, `results[ResultsKey.IMAGE]` holds a reference to the input image tensor, meaning throughout an epoch we'd be accumulating the entire dataset in GPU memory.
This PR mitigates this issue by simply removing the problematic tensor from the `results` dictionary, as this data is currently not used in our workflows.
=> BUG: Mitigate DeepMIL GPU memory leak in results dict

hi-ml-histopathology/environment.yml, hi-ml-histopathology/src/histopathology/models/encoders.py, hi-ml/run_requirements.txt
To enable DeepMIL fine-tuning experiments, this PR addresses two issues:
* Fix the setup of `SSLEncoder` to ensure there are no unused parameters (which breaks DDP);
* Pin `torch=1.10` to ensure compatibility with A100 GPUs (this was being overridden to 1.11 by the `torch>=10` in `hi-ml/run_requirements.txt`).
=> BUG: Fix SSL encoder setup and pin versions to support A100 GPUs

hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/model_trainer.py, hi-ml/testhiml/testhiml/test_model_trainer.py
- Add flag `--pl_limit_test_batches` to limit the number of test batches (similar to our current flags `--pl_limit_train_batches` and `--pl_limit_val_batches`
- Update `test_create_lightning_trainer_limit_batches` to include limiting test batches
=> ENH: Add flag pl_limit_test_batches

.vscode/settings.json
This is to remove trailing newlines and whitespaces, and adding a newline at the end of a file when saving.
=> STYLE: Add some formatting settings for VS Code

hi-ml/other/image_loading/profile_image_loading.py
The AML dataset panda_tiles (which is a subset of 61 PANDA_tiles files) will be renamed to panda_tiles_small, in order not to confuse with the full-size PANDA_tiles dataset
=> STYLE: Rename panda_tiles to panda_tiles_small

hi-ml-histopathology/src/histopathology/configs/classification/BaseMIL.py, hi-ml-histopathology/src/histopathology/models/deepmil.py
In this PR:
- A parameter `chunk_size` is added to `BaseDeepMILModule`. In `BaseMILTiles`, this is set to `encoding_chunk_size` which is an existing parameter of the container. 
- When `chunk_size`> 0, tiles are encoded in chunks of size `chunk_size`. This can avoid out-of-memory errors for large WSI.
- WSI validation and test is possible by using `max_bag_size_inf=0`.
=> ENH: Encoding in chunks to enable WSI validation and test

hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py
Fixes [the following issue](https://github.com/microsoft/hi-ml/issues/329) i.e. allows us to override list parameters that are not empty by default with empty lists
=> BUG: Add ability to override non-empty list params with empty

hi-ml-histopathology/src/histopathology/configs/classification/BaseMIL.py
So far we've hard-coded validation AUROC as the primary metric for checkpointing and saving outputs. This PR adds the option to customise it depending on the experiment (keeping val. AUROC as default for now).
=> ENH: Enable selection of primary validation metric in BaseMIL

hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py
Currently we always pass `wait_for_completion=False` to `submit_to_azure`. This change enables the user to override this to `wait_for_completion=True` via the commandline
=> ENH: Add param 'wait_for_completion' to ExperimentConfig

hi-ml-histopathology/src/histopathology/datasets/panda_tiles_dataset.py
This is not really a bug, but I couldn't think of a better tag.
Now that
- #311 and
- #321
have been merged, I have generated the new PANDA tiles dataset, which ~is being~ has been copied to our Azure container.
~I will remove the draft status once the transfer is finished.~
=> BUG: Update path to PANDA tiles directory

hi-ml-azure/src/health_azure/paths.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_paths.py, hi-ml/src/health_ml/utils/common_utils.py, hi-ml/testhiml/testhiml/utils/test_common_utils.py
When splitting repo into multiple workspaces, `hi-ml/environment.yml` was moved to  `hi-ml/hi-ml/environment.yml`.  The logic in get_all_environment_files is therefore out of date.
Also update check_conda_environments along the same lines, and add/ update tests for all of the above.
=> BUG: Update get_all_environment_files after environment.yml has moved

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-azure/testazure/testazure/test_himl.py
Add function that checks the number of nodes that have been specified for an AML job and checks that number is less than or equal to the maximum number of nodes allowed for the cluster.
Also small refactoring to separate out another cluster validation step into its own function. Tests added for all of the above.
=> ENH: Validate the number of requested nodes for an AML job

hi-ml-histopathology/src/histopathology/configs/SSL/PANDA_SimCLRContainer.py, hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILEPanda.py, hi-ml-histopathology/src/histopathology/datasets/base_dataset.py, hi-ml-histopathology/src/histopathology/datasets/default_paths.py, hi-ml-histopathology/src/histopathology/datasets/panda_tiles_dataset.py
In this PR:
- Paths are updated to point to the new PANDA tiles dataset created by @fepegar in https://github.com/microsoft/hi-ml/pull/325
- Columns `left` and `top` in the new tiles CSV are mapped to `tile_x` and `tile_y` of TilesDataset as the latter are being used to save batch outputs.
=> BUG: Update paths and columns for PANDA tiles dataset  

README.md
It looks like this:
[![codecov](https://codecov.io/gh/microsoft/hi-ml/branch/main/graph/badge.svg?token=kMr2pSIJ2U)](https://codecov.io/gh/microsoft/hi-ml)
=> DOC: Add Codecov badge to README

hi-ml-azure/setup.py, hi-ml/setup.py
Because we renamed a workflow, run number counting started back at 1. This now creates version clashes with the existing test.pypi packages from the very early days where run numbers also started at 1. Resolve by using a different prefix
=> BUG: Fix problem with Test.PyPi upload filename conflicts

.codecov.yml, .github/workflows/hi-ml-pr.yml, .github/workflows/histopathology-pr.yml
Using the [Codecov flags](https://docs.codecov.com/docs/flags) to get better reporting for monorepos
=> ENH: Group code coverage by folder

.pre-commit-config.yaml, hi-ml-histopathology/environment.yml, hi-ml-histopathology/requirements_test.txt, test_requirements.txt
Related to:
- #298
- #342
- #345
- #346
- #347
- #348
- #349
TODO:
=> ENH: Add pre-commit config file

docs/source/examples.md, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_himl.py
Adds a util function for reading the text contained in log files. Designed to work for boht `std_log.txt` (new runtime) and `70_driver_log.txt`. Used only once so far in hi-ml but has use in other tasks in InnerEye, such as [here](https://github.com/microsoft/InnerEye-Inference/issues/35).
=> ENH: Add log text reader function

hi-ml-histopathology/src/histopathology/datasets/default_paths.py, hi-ml-histopathology/src/histopathology/preprocessing/create_panda_tiles_dataset.py
Fixes #314.
Cucim adds black padding when loading slides using a bounding box that is not fully within the slide's field of view.
Some margin can be added to bounding boxes in `LoadPandaROId`, but that's not needed in this application.
This PR sets padding (`margin`) to 0 when creating the tiles dataset, therefore 
I will also upload the new data set to Azure and modify the dataset name in our code.
=> BUG: Remove padding when loading slides

hi-ml-histopathology/src/histopathology/utils/girder.py
This PR adds the `rescale` and `colormap` parameters to the script in the `girder` module, to improve flexibility and facilitate experimentation.
`Greens` is the default colormap because
1. It goes from white to a dark colour. This is nice because the slides background is typically white as well.
2. Green has the best contrast to the typical tissue colour (~magenta)
Rescaling is not performed by default because it might artificially emphasise attention values that are only slight larger than others. E.g., compare (0.04, 0.06, 0.95) and (0.32, 0.33, 0.34) with their rescaled equivalents: (0, 0.02, 1) and (0, 0.5, 1). The differences between values of the second array are very exaggerated. However, as pointed out in our meetings, this might not be relevant because the values depend on the …
=> ENH: Add visualization parameters to DSA annotations script

hi-ml-histopathology/src/histopathology/configs/SSL/HistoSimCLRContainer.py, hi-ml-histopathology/src/histopathology/configs/SSL/PANDA_SimCLRContainer.py, hi-ml-histopathology/src/histopathology/datasets/panda_tiles_dataset.py
In this PR, 
- Configuration for PANDA SSL is updated to run locally and on Azure ML.
- Docs are updated to explain `occupancy_threshold` and `random_subset_fraction` parameters in `PandaTilesDataset`.
- Parameter `random_subset_fraction` is added to `PandaTilesDataset` to select a random subset of tiles.
=> ENH: PANDA SSL with tile selection enabled (random or tile occupancy)

.github/workflows/histopathology-pr.yml, hi-ml-azure/run_pytest.py, hi-ml-histopathology/environment.yml
Add pytest_after_submission_hook to download pytest gpu test results and add it to codecov report.
=> ENH: Add gpu tests coverage to codecov reports

hi-ml-histopathology/environment.yml
Related to [issue 421](https://github.com/microsoft/hi-ml/issues/421)
The latest msrest does not work with azureml-core since `SerialisationError` and `DeserializationError` have been removed from the latest
=> ENH: Pin msrest to avoid missing import

hi-ml-histopathology/src/histopathology/scripts/mount_azure_dataset.py
Add path resolution before health_azure imports in mount_azure_dataset.py script.
=> BUG: Add path resolution in dataset mounting script

hi-ml/src/health_ml/runner.py
Currently, if the user specifies a relative path as `--conda_env`, it will be found by the first process which will then start training, and change the cwd to 'outputs'. This means that spawned processes can't find the relative conda_env path. This PR enables spawned processes to still find the conda env path
=> BUG: Stop looking for environment file if already running in AML

hi-ml-histopathology/src/histopathology/configs/classification/DeepSMILECrck.py
We use caching with pre-trained encoders in DeepMIL for TCGA-CRCk. This is now enabled by default in `DeepSMILECRCk` container through the `is_caching` parameter, by setting it to `True`. Also, `num_top_slides` is set to 0 by default, to avoid errors arising from caching in outputs handler for TCGA-CRCk.
=> BUG: Default parameters in `DeepSMILECRCk` container 

hi-ml-histopathology/Makefile
Recently I have been struggling to remember which command line options to specify for each model (e.g. `max_bag_size`, `is_caching` etc). Therefore, to make it easier to quickly run smoke tests (smaller versions of model training) with the correct parameters, I have added some commands to the Makefile.
Also adds back the TilesPandaImageNetMIL regression test since we decided to keep this, and updates the AML cluster to one that is available in the `hi-ml` Workspace
=> ENH: Add makefile commands for smoke tests

hi-ml-azure/Makefile, hi-ml-histopathology/Makefile, hi-ml/Makefile, multimodal/Makefile, new_project_template/Makefile
1. Show mypy error codes in output. That way, we can check and ignore specific errors in a readable way. For example, `# type: ignore[arg-type]` is probably better than `# type: ignore`.
1. Spell out argument name for readability
=> ENH: Improve mypy arguments

hi-ml-azure/run_requirements.txt, hi-ml-histopathology/environment.yml
Switch from the outdated AzureML package `azureml-sdk` to `azureml-core` and `azureml-train-core`. `azureml-dataset-runtime` is required to provide local mounting.
=> ENH: Switch from azureml-sdk to azureml-core

multimodal/health_multimodal/image/__init__.py, multimodal/health_multimodal/image/model/model.py, multimodal/health_multimodal/image/model/resnet.py, multimodal/requirements_run.txt, multimodal/test_multimodal/image/model/test_model.py
Addresses #464 
- Removes the dependency on pytorch-lightning and bolts.
- Wraps the torchvision resnet class to return the intermediate layer activations.
=> ENH: Remove the dependency on Lightning and Lightning Bolts

hi-ml-multimodal/notebooks/phrase_grounding.ipynb, hi-ml-multimodal/src/health_multimodal/text/__init__.py, hi-ml-multimodal/src/health_multimodal/text/utils.py, hi-ml-multimodal/test_multimodal/text/data/test_text_io.py, hi-ml-multimodal/test_multimodal/text/test_inference_engine.py, hi-ml-multimodal/test_multimodal/vlp/test_vlp_inference_engine.py
Use the "commit hash" to pull the CXR-BERT model from HuggingFace Hub.
Closes #481
=> ENH: Add commit ID when downloading CXR-BERT model

hi-ml-azure/.vscode/settings.json, hi-ml-histopathology/.vscode/settings.json, hi-ml-multimodal/.vscode/settings.json, hi-ml/.vscode/settings.json, himl-projects.code-workspace
VSCode often complains that many files are slowing it down. This solution is suggested in the documentation.
=> ENH: Exclude cache files from file watchers to speed up VSCode

.github/workflows/hi-ml-pr.yml
Rather than having 2 separate publishing tokens, use one with scope "all projects".
This is setting the stage for #501, and will simplify #472
=> ENH: Simplify publishing workflow by using a single PyPi token

docs/source/coding_guidelines.md
Small edit to PR title guidelines.
=> DOC: Use imperative for PR title in guidelines

.github/workflows/cpath-pr.yml
This avoids confusion from drop of coverage if GPU tests have not yet been accounted for.
=> ENH: Only upload codecov reports once

hi-ml-azure/src/health_azure/utils.py
I'm getting this error on Azure ML:
```python-traceback
Traceback (most recent call last):
File "radt5-dev/downstream_evaluation.py", line 142, in <module>
main()
File "radt5-dev/downstream_evaluation.py", line 138, in main
run(args)
File "radt5-dev/downstream_evaluation.py", line 131, in run
results = evaluate_tasks(args)
File "radt5-dev/downstream_evaluation.py", line 122, in evaluate_tasks
trivial_baseline=args.trivial_baseline,
File "radt5-dev/evaluation_utils/checkpoint.py", line 100, in get_model
load_for_inference=True,
File "radt5-dev/evaluation_utils/checkpoint.py", line 68, in get_pretrained_model
workspace_config_path=azure_params.workspace_config_path)
File "/azureml-envs/azureml_0bff92306a31e8d8ca795527d96b3826/lib/python3.7/site-packages/health_azure/utils.py", line 1035, in …
```
=> ENH: Show run ID and prefix if no files are found

hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml-cpath/src/health_cpath/utils/tiles_selection_utils.py
Clear the top and bottom slides heaps after every validation epoch. Otherwise `save_test_outputs` the slides in the results do not match those stored in the top and bottom slides heaps (which are only updated in the validation step)
=> BUG: Clear the top and bottom slides heaps after every validation epoch

hi-ml-multimodal/requirements_run.txt
When our code in Azure DevOps tries to install `hi-ml-multimodal`
```python-traceback
Traceback (most recent call last):
[...]
File "/azureml-envs/azureml_34426526264d358ffd2640a8d9fa6f09/lib/python3.7/site-packages/pl_bolts/utils/__init__.py", line 40, in <module>
_TORCHVISION_LESS_THAN_0_9_1: bool = _compare_version("torchvision", operator.ge, "0.9.1")
File "/azureml-envs/azureml_34426526264d358ffd2640a8d9fa6f09/lib/python3.7/site-packages/pl_bolts/utils/__init__.py", line 20, in _compare_version
[...]
File "/azureml-envs/azureml_34426526264d358ffd2640a8d9fa6f09/lib/python3.7/site-packages/torchvision/extension.py", line 101, in <module>
_check_cuda_version()
File "/azureml-envs/azureml_34426526264d358ffd2640a8d9fa6f09/lib/python3.7/site-packages/torchvision/extension.py", line 97, in …
```
=> BUG: Fix incompatibility between PIP and Conda CUDA versions

hi-ml-multimodal/src/health_multimodal/__init__.py, hi-ml-multimodal/src/health_multimodal/image/__init__.py, hi-ml-multimodal/src/health_multimodal/image/model/__init__.py, hi-ml-multimodal/src/health_multimodal/image/model/model.py, hi-ml-multimodal/src/health_multimodal/image/model/resnet.py, hi-ml-multimodal/src/health_multimodal/image/utils.py, hi-ml-multimodal/src/health_multimodal/text/utils.py, hi-ml-multimodal/test_multimodal/image/model/test_model.py, hubconf.py
This allows to run
```python
import torch
github = 'microsoft/hi-ml:add-hubconf'
model = torch.hub.load(github, 'biovil_resnet', pretrained=True)
image = torch.rand(1, 3, 480, 480)
output = model(image)
output.projected_patch_embeddings.shape  # prints torch.Size([1, 128, 15, 15])
```
It will work **even if `hi-ml-multimodal` is not installed**. Only `torch` and `torchvision` need to be installed. For that to be possible, I've had to do some not-so-nice refactoring, like declaring the same variable (Hugging Face constants) in two modules.
If this PR is merged, the snippet above won't need `:add-hubconf` and will use `main` by default.
=> ENH: Add hubconf to load models without installing

hi-ml-multimodal/test_multimodal/image/model/test_model.py
Specifying the branch when downloading a model using PyTorch Hub shouldn't be necessary, but an HTTP error was being raised anyway. There seem to have been issues with this in the past:
- https://github.com/pytorch/pytorch/pull/62139
- https://github.com/pytorch/pytorch/issues/61755
- https://github.com/n2cholas/jax-resnet/issues/4
- https://github.com/pytorch/pytorch/pull/61761
Explicitly specifying `main` seems to help, so I'm adding it to the test, and it should be included in any future documentation, just in case.
=> FIX: Hotfix HTTP error downloading model with hub

.github/workflows/cpath-pr.yml, hi-ml-cpath/Makefile, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILECrck.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILEPanda.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILESlidesPandaBenchmark.py, hi-ml-cpath/testhisto/testhisto/mocks/container.py
Add command line arg to enable custom SSL encoder checkpoint
This also allows us to add an additional smoke test for TcgaCrckSslMil which requires a checkpoint for the encoder
=> ENH: Enable custom SSL encoder checkpoint

hi-ml-cpath/src/health_cpath/datamodules/base_module.py, hi-ml-cpath/src/health_cpath/datasets/base_dataset.py
Add `dataframe_kwargs` to BaseDatasets and HistoDatamodule to be able to read only subset of csv and custom datatype
=> ENH: Add dataframe kwargs for flexible csv read

hi-ml-azure/run_requirements.txt, hi-ml-cpath/src/SSL/lightning_modules/ssl_online_evaluator.py, hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml/src/health_ml/run_ml.py, hi-ml/testhiml/testhiml/test_model_trainer.py, hi-ml/testhiml/testhiml/test_run_ml.py
Clean up logs
Please make sure to follow all the tasks in the checklist below. Then, delete this line and write a detailed description of your pull request here.
=> [DRAFT] Clean up logs (#565)

hi-ml-cpath/src/health_cpath/models/deepmil.py
Implicit dimension choice for softmax has been deprecated
=> ENH: Softmax requires dimension choice 

hi-ml-cpath/src/health_cpath/datasets/base_dataset.py
Index datasets dataframe by tile_id or slide_id only when necessary (e.g. the current index is not already to tile_id or slide_id  columns)
=> BUG: Set dataframe index column only when necessary

.github/workflows/cpath-pr.yml, hi-ml-cpath/Makefile, hi-ml-cpath/src/health_cpath/models/deepmil.py
Add a smoke test where all finetuning flags are switched on to make sure checkpoint loading and submodules initialization are completed properly.
=> ENH: Add smoke test for flexible finetuning

hi-ml-azure/src/health_azure/himl.py, hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/runner.py, hi-ml/testhiml/testhiml/test_runner.py
Add debug_ddp to assign different options to `TORCH_DISTRIBUTED_DEBUG` env variable.
=> ENH: Add debug_ddp flag

hi-ml-azure/setup.py, hi-ml-cpath/setup.py, hi-ml/setup.py
- Remove references to Health Intelligence from PyPi package info
- Use a consistent team name
- Use double quotes consistently in all `setup.py` files
=> DOC: Use a consistent team name across all packages

hi-ml-cpath/src/health_cpath/datasets/base_dataset.py, hi-ml-cpath/src/health_cpath/datasets/panda_dataset.py, hi-ml-cpath/src/health_cpath/datasets/panda_tiles_dataset.py, hi-ml-cpath/testhisto/testhisto/datasets/test_panda_slides.py, hi-ml-cpath/testhisto/testhisto/datasets/test_panda_tiles.py, hi-ml-cpath/testhisto/testhisto/mocks/slides_generator.py, hi-ml-cpath/testhisto/testhisto/mocks/tiles_generator.py
Use df.assign to fix SettingWithCopyWarning  warning and make metadata validation optional to be able to read only subsets of dataset csv
=> BUG: Fix SettingWithCopyWarning and parametrize metadata validation

hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml-cpath/src/health_cpath/utils/plots_utils.py
In this PR:
- Average precision metric is added to multi-class (n_classes > 1) case.
- AUROC is modified such that `num_classes=None` for binary case, as prescribed in Pytorch documentation https://torchmetrics.readthedocs.io/en/stable/classification/auroc.html.
- Parameter `num_classes` is not explicitly given in Specificity, similar to the other binary metrics.
- Hardcoded `threshold=0.5` is removed from binary metrics (since this is default value).
- Confusion matrix is normalized on true values.
- Metrics are re-organized for readability.
=> ENH: Add/reorganise metrics and correctly normalise confusion matrix

hi-ml/src/health_ml/run_ml.py, hi-ml/src/health_ml/utils/data_augmentations.py, hi-ml/testhiml/testhiml/test_data_augmentations.py, hi-ml/testhiml/testhiml/test_run_ml.py
Enable stain normalization to work with multiple images (e.g., when a bag of tiles is given as input).
=> ENH: Enable stain normalization for multiple images

hi-ml-cpath/src/health_cpath/utils/deepmil_utils.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/networks/layers/attention_layers.py, hi-ml/testhiml/testhiml/test_attentionlayers.py
In this PR:
- `transformer_dropout` parameter is added to `TransformerPooling` and `TransformerPoolingBenchmark` pooling layers.
- Tests are updated with the `transformer_dropout` parameter.
=> ENH: Dropout in transformer layers in DeepMIL

hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/model_trainer.py, hi-ml/testhiml/testhiml/test_model_trainer.py
Adding gradient accumulation flag to enable gradient accumulation in  Pytorch Lightening containers
=> ENH: Adding gradient accumulation flag to trainer

hi-ml-cpath/src/health_cpath/utils/tiles_selection_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_tiles_selection_utils.py
For small validation sets and poor performance models, we sometimes end up with some slides falsely belonging to TP/FN cases. 
We need to make sure thay top_heaps contain only true cases and bottom ones, only false cases.
Check predicted vs true label before pushing into slides_heaps to make sure we only push true predictions in top_slides_heaps and false ones in bottom_slides_heaps
=> BUG: Fix top bottom tiles selection mismatch.

hi-ml/src/health_ml/configs/hello_world.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/runner.py, hi-ml/testhiml/testhiml/test_runner.py
Add `get_additional_aml_run_tag` to LightningContainer to be able to add extra tags to aml runs to facilitate runs comparison and filtering.
=> ENH: Enable adding tags to aml runs from LightningContainer

hi-ml-cpath/src/health_cpath/scripts/generate_crossval_report.py, hi-ml-cpath/src/health_cpath/utils/analysis_plot_utils.py, hi-ml-cpath/src/health_cpath/utils/report_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_report_utils.py
* Add commandline arguments to parametrise child runs arg identifier and primary metric to get best_epoch.
* Rename all crossval functions to hyperdrive ones to make it generic
=> ENH: Make crossval html report generic to all hyperdrive runs

hi-ml-cpath/src/health_cpath/models/deepmil.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/configs/hello_world.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/run_ml.py, hi-ml/testhiml/testhiml/test_run_ml.py
Avoid accessing sensitive attributes from the runner
Add on_extra_val_epoch_start hook to avoid confusion
=> ENH: Refactor extra validation epoch logic

.amltignore, .gitignore, docs/source/amulet/amulet_script.py, docs/source/amulet/amulet_script.rst, docs/source/amulet/config.rst, docs/source/amulet/config.yml, docs/source/amulet/environment.rst, docs/source/amulet/environment.yml, docs/source/amulet_example.md, docs/source/amulet_overview.md, docs/source/index.rst, hello_world.yml, hi-ml-azure/src/health_azure/amulet.py, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml/src/health_ml/deep_learning_config.py, hi-ml/src/health_ml/runner.py, pyrightconfig.json
Merge #612 from main:
- Move all Amulet-related code to a separate module
- Add bug fix for `RANK` environment to `hi-ml` runner
- Improve documentation and add standalone example script
=> ENH: Improve Amulet support and documentation

docs/source/amulet/config.yml
This fixes the errors reported by http://www.yamllint.com/ and [pre-commit](https://results.pre-commit.ci/run/github/382004101/1665055387.-41Vk8XXSNe2Py8apajfxg):
```
while parsing a block mapping
in "docs/source/amulet/config.yml", line 1, column 1
did not find expected key
in "docs/source/amulet/config.yml", line 25, column 2
```
=> MNT: Fix YAML syntax for Amulet jobs

hi-ml/src/health_ml/runner.py
This solves the error that we encounter when submitting a cross validation run with Amulter via hi-ml runner that expect a cluster argument to be able to launch a crossvalidation. This is necessary as k folds splits are enabled for crossval_count > 1.
=> ENH: Enable running cross validation via amulet

hi-ml-azure/testazure/testazure/test_datasets.py
I accidentally created a v2 data asset with the same name as a v1 dataset in our test suite. The data asset cannot be removed or renamed, hence I am renaming the v1 dataset in the test to get it passing again
=> FIX: Fix test_get_dataset

hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILEPanda.py, hi-ml-cpath/src/health_cpath/utils/naming.py, hi-ml-cpath/src/health_cpath/utils/output_utils.py, hi-ml-cpath/src/health_cpath/utils/plots_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_plots_utils.py
Dissociate thumbnails and heatmaps plots to flexibly remove/add each of these plot options. 
Motivations: thumbnail plots can be costly, so we might want to omit it sometime while including heatmap plots and vice versa.
=> ENH: Separate attention heatmap and slide thumbnail plot options

hi-ml-azure/src/health_azure/utils.py, hi-ml-cpath/src/health_cpath/scripts/generate_crossval_report.py, hi-ml-cpath/src/health_cpath/utils/analysis_plot_utils.py, hi-ml-cpath/src/health_cpath/utils/naming.py, hi-ml-cpath/src/health_cpath/utils/report_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_report_utils.py
In this PR:
- Fix is introduced to handle missing cross-validation rounds (e.g., when a round fails)
- Extra validation epoch is handled
- Downloading the AML metrics json and saving it as a dataframe is separated into two functions (current version gives a `KeyError` when the json is downloaded for the first time)
=> BUG: Fix HTML report 

hi-ml/src/health_ml/utils/lightning_loggers.py
log_hyperparameters fails with ChainedTokenCredential failure because we were using an mlflow client that is not linked to the local tracking uri so it was trying to authenticate to Azure to retrieve the run.
=> BUG: Fix mlflow authentication error 

hi-ml-azure/src/health_azure/himl.py
v2 get_ml_client and therefore get_credential gets called when using --strictly_azureml_v1. Here we move this call to v2 scope only to be able to use v1 strictly
=> BUG: Move MlClient call to v2 scope only

hi-ml/src/health_ml/runner.py
There was still another call to get_ml_client that was asking for credentials again preventing running on aml v1 strictly
=> BUG: Remove all calls to get_ml_client outside v2

.pre-commit-config.yaml, docs/source/checkpoints.md
Fixes this https://results.[pre-commit.ci](https://results.pre-commit.ci/run/github/382004101/1668608031.nWPPLzbPRtmEbrD7tUrs0Q)/run/github/382004101/1668608031.nWPPLzbPRtmEbrD7tUrs0Q
=> BUG: Use permanent permalinks in docs to fix precommit check

hi-ml-cpath/src/health_cpath/models/deepmil.py
the default for MultiClassAccuracy is macro [Accuracy — PyTorch-Metrics 0.10.3 documentation (torchmetrics.readthedocs.io)](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html#multiclassaccuracy)
But base class (which we were using before) is micro [Accuracy — PyTorch-Metrics 0.10.3 documentation (torchmetrics.readthedocs.io)](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html)
We need to set average=micro
=> BUG: Use micro average for MultiClassAccuracy

hi-ml-azure/src/health_azure/utils.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/runner.py, hi-ml/testhiml/testhiml/test_runner.py
add get_additional_environment_variables to Lightning container to be able to flexibly add experiments specific env variables, e.g. Azure mounting env variables for large file experiments... this can be overridden in the config file directly.
=> ENH: Enable adding additional env variables from container

.github/pull_request_template.md
The list of valid prefixes is out of date. Instead of manually syncing with the docs, I propose linking to them.
=> DOC: Refer to CONTRIBUTING for list valid prefixes

hi-ml-cpath/src/health_cpath/datamodules/base_module.py
add get_tiling_transforms to be able to flexibly override tiling on the fly steps in case we need to add additional preprocessing before tiling, like normalizing the background...
=> ENH: Enable overriding tiling on the fly steps

hi-ml-cpath/src/health_cpath/preprocessing/create_tiles_dataset.py
Option 'only' added to the tiling script. Only behaves the same as in the script used for cropping: A single slide ID is given. Was useful for debugging low contrast slides.
=> ENH: Add option to tile a single slide selected by slide id

hi-ml-cpath/testhisto/testhisto/datamodules/test_slides_datamodule.py, hi-ml-cpath/testhisto/testhisto/mocks/slides_generator.py
Closes #716 
Test with OpenSlide backend as well now that the tiffiles are not corrupted anymore -> properly compressed and saved in chunks by specifying tile_size in tiffwriter options
=> BUG: Fix slow-path warning in tests that use MockPandaSlidesGenerator

docs/source/checkpoints.md, hi-ml-azure/src/health_azure/package_setup.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_azure_util.py, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/utils/deepmil_utils.py, hi-ml-cpath/testhisto/testhisto/utils/test_deepmil_utils.py, hi-ml/src/health_ml/run_ml.py, hi-ml/src/health_ml/utils/checkpoint_handler.py, hi-ml/src/health_ml/utils/checkpoint_utils.py, hi-ml/testhiml/testhiml/test_checkpoints.py
Jobs that get interrupted after training and then re-start will not find an inference checkpoint and fail. This PR adds logic to search for that checkpoint in AzureML.
Closes #701
=> ENH: Allow low-priority preemption after training

hi-ml-multimodal/.bumpversion.cfg, hi-ml-multimodal/Makefile, hi-ml-multimodal/requirements_test.txt, hi-ml-multimodal/setup.py, hi-ml-multimodal/src/health_multimodal/__init__.py
Bumping version to include @markpinnock's changes from #724.
Additionally, I've added some convenience tools for semi-automatic bumping with `make`. For example:
```shell
make bump_version part=patch
```
Next, I will run the commands in https://github.com/microsoft/hi-ml/pull/545#issue-1324136707 (which could also become a `make` command) to publish the new version.
TODO:
=> MNT: Bump hi-ml-multimodal patch version

hi-ml-azure/Makefile, hi-ml-cpath/Makefile, hi-ml/Makefile
For diagnosing slow running tests, add the `--durations` flag to `pytest` to have it print the slowest N tests
=> ENH: Output the slowest tests

hi-ml/src/health_ml/runner.py
in line 210 we get_workspace with the specified workspace_config_path, so we just need to pass it to get_ml_client to prevent it from using the default config path
Any suggestions for testing?
Closes #755
=> BUG: ML Client doesn't use workspace config path when specified

hi-ml-azure/src/health_azure/datasets.py, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_datasets.py, hi-ml-azure/testazure/testazure/test_himl.py
=> BUG: Fix create v2 asset bug

hi-ml-cpath/src/health_cpath/scripts/generate_checkpoint_url.py
Enables to specify a different workspace config path to generate checkpoint URLs
=> ENH: Add workspace config path to generate checkpoint URL script

hi-ml-multimodal/src/health_multimodal/image/model/model.py, hi-ml-multimodal/test_multimodal/image/model/test_model.py
When guessing the number of output dimensions in the image encoder, the model is in training mode and the batch norm stats get updated. This shouldn't really happen and makes the checks in https://github.com/microsoft/hi-ml/pull/807/files#r1112200449 fail. This PR adds a line to ensure the encode is in `eval` mode before calculating the number of output dims.
=> FIX: Set evaluation mode to compute number of dimensions

hi-ml-multimodal/Makefile
Running `make publish` from `/hi-ml-multimodal` will publish the package to PyPI. It can be tested before by running `make publish_test`.
=> MNT: Add make command to publish to PyPI

.gitignore, docs/Makefile, docs/source/CHANGELOG.md, docs/source/CONTRIBUTING.md, docs/source/multimodal.md
Fixes #823.
There was an issue with the Azure ML Python SDK v2 disliking symlinks in the source dir, but that seems to have been resolved now so this PR removes the copying operation and replaces the targets with symlinks.
=> DOC: Use symlinks to build docs instead of copying files

hi-ml/src/health_ml/utils/regression_test_utils.py, hi-ml/testhiml/testhiml/test_regression_test_utils.py
When there is a mismatch in regression metrics, too many lines are printed out.
=> BUG: Misleading warnings when comparing metrics

hi-ml/src/health_ml/experiment_config.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/runner.py, hi-ml/testhiml/testhiml/test_runner.py
Based on a commandline flag, models can now switch between different hyperparameters
=> ENH: Allow variants of model parameters in the same class

hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/src/health_cpath/models/encoders.py, hi-ml-cpath/src/health_cpath/utils/deepmil_utils.py
Refactor Swin Transformer checkpointing to enable patch embedding checkpointing overriding without duplication the whole custom forward
=> ENH: Refactor Swin Transformer checkpointing

hi-ml-multimodal/src/health_multimodal/image/model/encoder.py, hi-ml-multimodal/src/health_multimodal/image/model/pretrained.py, hi-ml-multimodal/src/health_multimodal/image/model/types.py, hi-ml-multimodal/test_multimodal/image/model/test_encoder.py, hi-ml-multimodal/test_multimodal/image/model/test_pretrained.py
This PR allows the user to determine whether to use ResNet weights pre-trained on ImageNet or BioViL, or whether to have a randomly initialised model: fixes #617  .
=> ENH: Improve support for choosing image model weights

hi-ml/src/health_ml/runner_base.py, hi-ml/src/health_ml/training_runner.py, hi-ml/testhiml/testhiml/test_training_runner.py
Fix the order of hook call. on_run_extra_val_epoch needs to be run before super().init_inference to account for any changes in datamodule params before re-instantiation
=> BUG: Fix extra validation epoch hook call order

hi-ml-cpath/src/health_cpath/scripts/generate_checkpoint_url.py, hi-ml-cpath/testhisto/testhisto/utils/test_deepmil_utils.py
Some datastores don't have access to account key, so we need a way of specifying it via commandline
=> ENH: Add account key argument to generate checkpoint URL script 

hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILEPanda.py, hi-ml-cpath/src/health_cpath/configs/classification/DeepSMILESlidesPandaBenchmark.py, hi-ml-cpath/src/health_cpath/datamodules/panda_module.py, hi-ml-cpath/src/health_cpath/datamodules/panda_module_benchmark.py, hi-ml-cpath/src/health_cpath/datasets/base_dataset.py, hi-ml-cpath/src/health_cpath/datasets/panda_dataset.py, hi-ml-cpath/src/health_cpath/datasets/tcga_prad_dataset.py, hi-ml-cpath/src/health_cpath/scripts/tcga_dataset_prep.py, hi-ml-cpath/src/health_cpath/utils/montage.py, hi-ml-cpath/src/health_cpath/utils/tiff_conversion_config.py, hi-ml-cpath/testhisto/testhisto/datasets/test_panda_slides.py, hi-ml-cpath/testhisto/testhisto/mocks/slides_generator.py, hi-ml-cpath/testhisto/testhisto/utils/test_montage.py
Metadata columns are presently set via class variables, rather than in the constructor. Hence, we can't have several datasets that use different metadata columns, without them interfering with each other. This caused odd test failures because test results now depend on the order in which tests are executed.
=> ENH: Clean up design of slides dataset

hi-ml/.vscode/settings.json, hi-ml/testhiml/testhiml/test_training_runner.py
Ensure that the test set metrics are correctly reproduced when using the runner in inference-only mode
=> ENH: Add tests for use of checkpoints in inference_only mode

hi-ml-azure/src/health_azure/himl.py
Fix so no arguments are passed to the submitted script when an empty list is explicitly passed to `script_params` in `submit_to_azure_if_needed`.
=> FIX: Fix empty list of script params not used

hi-ml-cpath/src/health_cpath/preprocessing/tiff_conversion.py, hi-ml-cpath/testhisto/testhisto/preprocessing/test_tiff_conversion.py
TIFF conversion fails if input resolution is not in centimeters, but we don't rely on that being the case. Hence, remove the error message and just print an info line
=> BUG: TIFF conversion enforces resolution unit to be centimeter

hi-ml-azure/src/health_azure/himl.py, hi-ml-cpath/src/health_cpath/configs/classification/BaseMIL.py, hi-ml-cpath/testhisto/testhisto/models/test_deepmil.py, hi-ml/src/health_ml/lightning_container.py, hi-ml/src/health_ml/runner_base.py, hi-ml/src/health_ml/utils/split_dataset.py, hi-ml/testhiml/testhiml/test_split_dataset.py
Instantiating the DeepMIL classifier in `create_model` always relies on the training dataset and module, which is not available when doing evaluation. This PR makes that more flexible and allows to hardcode the number of classes to use for evaluation.
=> BUG: DeepMIL model uses training data even when running in eval mode

hi-ml-cpath/src/health_cpath/preprocessing/tiff_conversion.py
svs has different metadata properties than Tiff and NDPI. This fix handles the case when get_mpp from monai fails with a KeyError exception missing "Tiff.XResolution" and "Tiff.YResolution"
=> BUG: Fix KeyError when converting svs to tiff

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py, hi-ml-cpath/requirements_run.txt
This PR removes the check for available number of nodes, meaning the code will run just fine on any type of compute.
Closes #901
=> BUG: Enable submitting jobs to compute instances

.github/workflows/hi-ml-pr.yml
Remove pyright from PR builds. At present, this constantly fails because the disk is full. This blocks the release of new packages
=> MNT: Disable PyRight

hi-ml-azure/run_requirements.txt, hi-ml-azure/src/health_azure/auth.py, hi-ml-azure/src/health_azure/utils.py, hi-ml-azure/testazure/testazure/test_get_ml_client.py, hi-ml-azure/testazure/testazure/test_get_workspace.py
At present, only ServicePrincipal and InteractiveAuthentication are supported for AzureML SDK v1. This PR adds AzureCLI as a third option. This sets the stage for password-free authentication in pipelines
=> ENH: Add AzureCLI authentication for SDK v1 codepath

hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
Currently when calling `submit_to_azure_if_needed` with `submit_to_azureml=True`, python is exited after the job is submitted. This PR adds an option `exit_on_completion` to control whether this happens. If `exit_on_completion` is `False` then the submitted `Run`/`Job` objects are returned.
=> ENH: Add support to return the job after submitting a run

.github/workflows/cpath-pr.yml, .github/workflows/hi-ml-pr.yml
We are getting this surprising message in our CI because we're using an old version of the GHA to publish packages:
This PR uses the recommended ref for the GHA.
=> MNT: Update ref of pypa/gh-action-pypi-publish

.github/actions/upload_package_artifacts/action.yml
The CI for uploading package artefacts is failing with the following error:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
This PR switches the Github action `upload-artifact` to v4.
=> FIX: Switch to upload artefact v4

.github/actions/download_package_artifacts/action.yml, .github/actions/upload_package_artifacts/action.yml, hi-ml-azure/src/health_azure/himl.py, hi-ml-azure/testazure/testazure/test_himl.py
Currently submitting a hyperdrive run assumes that all sweep distributions are `Choice`. This PR adds support for other sweep types described [here](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.sweep?view=azure-python) for SDK v2 jobs.
If hydra is used for command line arguments then `/` or `.` will be in the argument names which is not supported as an input type or argument name for `command_job`. As such, these get replaced with `_`.
=> ENH: Add support for other hyperdrive sweep types

hi-ml-azure/setup.py, hi-ml-cpath/setup.py, hi-ml-multimodal/setup.py, hi-ml/setup.py
PyPI will require all newly uploaded source distribution filenames to comply with PEP 625. The filename must contain the normalized project name with underscores, so it's `hi_ml_azure` instead of `hi-ml-azure`
=> MNT: Switch release packages to normalized names
